site_name: L3-SNIO Outils Informatiques
site_url: https://sitename.example
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  icon:
    logo: fontawesome/solid/d
  favicon: assets/d-letter.svg
  features:
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.tabs
    - navigation.sections
    - content.tabs.link
  language: fr
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: lime

# Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

nav:
  - Accueil: index.md
  - I. Fondamentaux:
    - Environnement: Fondamentaux/environnement.md
    - IDE: Fondamentaux/ide.md
    - Commandes Linux: Fondamentaux/commandes_linux.md
  - II. Python:
    - Bases: Python/bases.md
    - NumPy: Python/numpy.md
    - Pandas: Python/pandas.md
    - Visualisation: Python/matplotlib.md
  - III. Julia:
    - Introduction: Julia/introduction.md
    - Optimisation: Julia/optimisation.md
    - Comparaison Python: Julia/vs_python.md
  - Évaluations:
    - Quiz: Evaluations/quiz.md
    - Projets: Evaluations/projets.md


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid 
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details

copyright: |
  &copy; 2025 Centre de recherche Christiaan Huygens, Réalisé par <a href="https://github.com/eberoFF"  target="_blank" rel="noopener">Lyam Rylewski</a>
